[package]
name = "cosigner"
version = "0.1.0"
edition = "2021"

[lib]
name = "cosigner"
path = "src/lib.rs"

[[bin]]
name = "cosigner"
path = "src/main.rs"

[dependencies]
anyhow = "1"
bitcoin = { version = "0.32.8", features = ["base64"] }
clap = { version = "4.6", features = ["derive"] }
miniscript = { version = "12.3.7", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
